name: Graphidget # プロジェクト名

options:
  deploymentTarget:
    iOS: 14.0 # 対象下限iOSバージョン
  xcodeVersion: "12.0.1"
  developmentLanguage: ja

packages:
  Charts:
    url: https://github.com/danielgindi/Charts
    version: 3.6.0

settings: # Project の Build Setting
  base: # Project全体設定
    DEVELOPMENT_TEAM: 3537BAHE48
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  configs: # Configurationごとの設定
    Release:
      VALIDATE_PRODUCT: true # 生成されたProductに対して検証テストを行うかどうか

targets:
  Graphidget: # iOSアプリ本体のターゲット
    type: application
    platform: iOS
    sources:
      - Graphidget
      - path: GraphidgetWidget/GraphidgetWidget.intentdefinition
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.altive.Graphidget
        PRODUCT_NAME: $(TARGET_NAME)
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Graphidget/Info.plist
        # CODE_SIGN_ENTITLEMENTS: Graphidget/Graphidget.entitlements
        DEVELOPMENT_LANGUAGE: jp
        DEVELOPMENT_ASSET_PATHS: "\"Graphidget/Preview Content\""
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        ENABLE_PREVIEWS: true
    dependencies:
      - target: GraphidgetWidget
      - package: Charts
        
    # preBuildScripts: # ビルド前に実行するスクリプト（R.swift, Mockoloなど）
    postCompileScripts: # ビルド後に実行するスクリプト（SwiftLintなど）
      # SwiftLintで静的解析と自動修正
      - script: |
                if which mint >/dev/null; then
                  mint run swiftlint swiftlint autocorrect --format
                  mint run swiftlint swiftlint
                else
                  echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
                fi
        name: Run SwiftLint

  GraphidgetTests: # 単体テストのターゲット
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: GraphidgetTests/Info.plist
    sources:
      - GraphidgetTests
    dependencies:
      - target: Graphidget # 本体アプリターゲットに依存

  GraphidgetUITests: # UIテストのターゲット
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: GraphidgetUITests/Info.plist
    sources:
      - GraphidgetUITests
    dependencies:
      - target: Graphidget # 本体アプリターゲットに依存

  GraphidgetWidget: # Widget Extension
    type: app-extension
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.altive.Graphidget.GraphidgetWidget
        INFOPLIST_FILE: GraphidgetWidget/Info.plist
        SKIP_INSTALL: true
        PRODUCT_NAME: $(TARGET_NAME)
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    sources:
      - GraphidgetWidget
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework


schemes:
  Graphidget:
    build:
      targets:
        Graphidget: all
        GraphidgetTests: [test]
        GraphidgetUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Graphidget
      targets:
        - name: GraphidgetTests
          parallelizable: true # テストを並行して実行するかどうか。Default: false
          randomExecutionOrder: true # ランダムな順序でテストを実行するかどうか。Default: false
        - name: GraphidgetUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
    
  GraphidgetWidgetExtension:
    build:
      targets:
        GraphidgetWidget: all
        Graphidget: all
    run:
      config: Debug
      askForAppToLaunch: true
      debugEnabled: false
      environmentVariables:
        - variable: _XCWidgetKind
          value:
          isEnabled: false
        - variable: _XCWidgetDefaultView
          value: timeline
          isEnabled: false
        - variable: _XCWidgetFamily
          value: medium
          isEnabled: false
    test:
      config: Debug
    profile:
      config: Release
      askForAppToLaunch: true
    analyze:
      config: Debug
    archive:
      config: Release
