name: CI

on:
  push:
    branches: [ develop ]
    paths-ignore: 
      - README.md
  pull_request:
    branches: [ develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.app

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Mint
      run: brew install mint
    
    - name: Cache Mint packages
      uses: actions/cache@v2.1.2
      with:
        path: mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-
          
    - name: Mint bootstrap
      run: mint bootstrap
      
    - name: XcodeGen generate
      run: mint run xcodegen xcodegen generate
    
    - name: Xcode Build
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -scheme Graphidget
        build
        | xcpretty
        
    - name: Xcode Test
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -scheme Graphidget
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
        clean test
        | xcpretty --report html
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: test-results
        path: build/reports
